declare module "lucide-react" {
  import { FC, SVGProps } from "react"
  export const ArrowRight: FC<SVGProps<SVGSVGElement>>
  export const BookOpen: FC<SVGProps<SVGSVGElement>>
  export const Sparkles: FC<SVGProps<SVGSVGElement>>
  export const Layers: FC<SVGProps<SVGSVGElement>>
  export const Download: FC<SVGProps<SVGSVGElement>>
  export const MessageSquare: FC<SVGProps<SVGSVGElement>>
  export const GraduationCap: FC<SVGProps<SVGSVGElement>>
  export const LayoutDashboard: FC<SVGProps<SVGSVGElement>>
  export const CalendarCheck: FC<SVGProps<SVGSVGElement>>
  export const FileText: FC<SVGProps<SVGSVGElement>>
  export const FileSpreadsheet: FC<SVGProps<SVGSVGElement>>
  export const Pencil: FC<SVGProps<SVGSVGElement>>
  export const ClipboardCheck: FC<SVGProps<SVGSVGElement>>
  export const CheckSquare: FC<SVGProps<SVGSVGElement>>
  export const FolderOpen: FC<SVGProps<SVGSVGElement>>
  export const Settings: FC<SVGProps<SVGSVGElement>>
  export const Building2: FC<SVGProps<SVGSVGElement>>
  export const ChevronLeft: FC<SVGProps<SVGSVGElement>>
  export const ChevronRight: FC<SVGProps<SVGSVGElement>>
  export const Search: FC<SVGProps<SVGSVGElement>>
  export const MoreVertical: FC<SVGProps<SVGSVGElement>>
  export const Trash2: FC<SVGProps<SVGSVGElement>>
  export const Share2: FC<SVGProps<SVGSVGElement>>
  export const Copy: FC<SVGProps<SVGSVGElement>>
  export const Plus: FC<SVGProps<SVGSVGElement>>
  export const Loader2: FC<SVGProps<SVGSVGElement>>
  export const Sun: FC<SVGProps<SVGSVGElement>>
  export const Moon: FC<SVGProps<SVGSVGElement>>
  export const LogOut: FC<SVGProps<SVGSVGElement>>
  export const User: FC<SVGProps<SVGSVGElement>>
  export const CreditCard: FC<SVGProps<SVGSVGElement>>
  export const Bot: FC<SVGProps<SVGSVGElement>>
  export const Send: FC<SVGProps<SVGSVGElement>>
  export const BarChart3: FC<SVGProps<SVGSVGElement>>
  export const Users: FC<SVGProps<SVGSVGElement>>
  export const MoreHorizontal: FC<SVGProps<SVGSVGElement>>
  export const X: FC<SVGProps<SVGSVGElement>>
  export const Check: FC<SVGProps<SVGSVGElement>>
  export const ChevronDown: FC<SVGProps<SVGSVGElement>>
  export const Menu: FC<SVGProps<SVGSVGElement>>
  export const ChevronDownIcon: FC<SVGProps<SVGSVGElement>>
  export const ChevronUpIcon: FC<SVGProps<SVGSVGElement>>
  export const ChevronRightIcon: FC<SVGProps<SVGSVGElement>>
  export const ChevronLeftIcon: FC<SVGProps<SVGSVGElement>>
  export const MoreHorizontalIcon: FC<SVGProps<SVGSVGElement>>
  export const CheckIcon: FC<SVGProps<SVGSVGElement>>
  export const XIcon: FC<SVGProps<SVGSVGElement>>
  export const SearchIcon: FC<SVGProps<SVGSVGElement>>
  export const CircleCheckIcon: FC<SVGProps<SVGSVGElement>>
  export const InfoIcon: FC<SVGProps<SVGSVGElement>>
  export const TriangleAlertIcon: FC<SVGProps<SVGSVGElement>>
  export const OctagonXIcon: FC<SVGProps<SVGSVGElement>>
  export const Loader2Icon: FC<SVGProps<SVGSVGElement>>
}
