import Link from "next/link"
import { Sparkles } from "lucide-react"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "AI Lesson Planner terms of service - rules and guidelines for using our platform.",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <header className="border-b">
        <div className="container mx-auto flex h-16 items-center px-4">
          <Link href="/" className="flex items-center gap-2 font-bold text-xl">
            <Sparkles className="h-6 w-6 text-primary" />
            AI Lesson Planner
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 py-16 max-w-3xl">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString("en-KE", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="space-y-6">
          <Section title="1. Acceptance of Terms">
            <p>By accessing or using AI Lesson Planner (&quot;the Platform&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>AI Lesson Planner is an AI-powered platform that helps teachers generate CBC-aligned teaching documents including lesson plans, schemes of work, assessments, and other educational resources. The Platform uses artificial intelligence to assist with content generation.</p>
          </Section>

          <Section title="3. User Accounts">
            <p>You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate, current, and complete information during registration. You are solely responsible for all activities that occur under your account.</p>
          </Section>

          <Section title="4. Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Use the Platform for any unlawful purpose or in violation of any applicable laws</li>
              <li>Attempt to access, probe, or scan the Platform&apos;s infrastructure without authorization</li>
              <li>Interfere with or disrupt the Platform&apos;s security features</li>
              <li>Generate content that is harmful, discriminatory, or inappropriate for educational settings</li>
              <li>Share your account credentials with unauthorized users</li>
              <li>Resell or redistribute the Platform&apos;s services without written permission</li>
            </ul>
          </Section>

          <Section title="5. Subscription and Billing">
            <p>We offer various subscription plans as described on our pricing page. By subscribing, you agree to pay the applicable fees. Subscriptions auto-renew unless cancelled. Refunds are handled according to our Refund Policy. We use Stripe for payment processing and do not store your payment card details.</p>
          </Section>

          <Section title="6. Content Ownership">
            <p>You retain ownership of all content you generate using the Platform. By using the Platform, you grant us a limited license to store, process, and display your content solely for the purpose of providing the service. We do not claim ownership over any content generated through AI assistance.</p>
          </Section>

          <Section title="7. AI-Generated Content">
            <p>Content generated by AI is provided as a starting point and should be reviewed by the teacher for accuracy, appropriateness, and alignment with curriculum requirements. We are not liable for errors, omissions, or inappropriate content generated by the AI. Teachers retain professional responsibility for all content used in their classrooms.</p>
          </Section>

          <Section title="8. Intellectual Property">
            <p>The Platform name, logo, and brand elements are our trademarks. The underlying technology, algorithms, and software are protected by intellectual property laws. You may not copy, modify, distribute, or reverse engineer any part of the Platform.</p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>The Platform is provided &quot;as is&quot; without warranties of any kind. We shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform. Our total liability shall not exceed the amount you paid for the subscription during the 12 months preceding the claim.</p>
          </Section>

          <Section title="10. Termination">
            <p>We may suspend or terminate your access to the Platform for violation of these Terms. You may cancel your account at any time from your settings page. Upon termination, your data will be retained for 30 days before permanent deletion.</p>
          </Section>

          <Section title="11. Governing Law">
            <p>These Terms shall be governed by the laws of the Republic of Kenya. Any disputes shall be resolved through arbitration in accordance with Kenyan law.</p>
          </Section>

          <Section title="12. Changes to Terms">
            <p>We reserve the right to modify these Terms at any time. We will notify users of material changes via email or platform notification. Continued use after changes constitutes acceptance of the new Terms.</p>
          </Section>

          <Section title="13. Contact">
            <p>For questions about these Terms, please contact us:</p>
            <p className="text-muted-foreground">Email: legal@ailessonplanner.com</p>
          </Section>
        </div>
      </main>

      <footer className="border-t py-8">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
          &copy; {new Date().getFullYear()} AI Lesson Planner. All rights reserved.
        </div>
      </footer>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-2xl font-semibold mb-4">{title}</h2>
      <div className="text-muted-foreground space-y-3 leading-relaxed">{children}</div>
    </section>
  )
}
